learning_templates/basicapp/urls.py
from django.urls import path
from basicapp import views


#For template tagging
app_name = 'basicapp'


urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('', include('basicapp.urls')),
]

learning_templates/basicapp/models.py
from django.db import models

# Create your models here.

learning_templates/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict = {'text': 'hello world', 'number': 1000}
    return render(request, 'basicapp/index.html', context_dict)


def other(request):
    return render(request, 'basicapp/other.html')


def relative(request):
    return render(request, 'basicapp/relurltemplates.html')

learning_templates/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=s, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a></li>
                
            </ul>
        </div>
    </nav>
    <div class="container">
        <h1>Welcome to the base page</h1>
        {% block body_block %}

        <!-- #Anything outside this block is setting -->

        {% endblock %}
    </div>
    
</body>
</html>

learning_templates/templates/basicapp/index.html
<!DOCTYPE html>

{% extends  "basicapp/base.html" %}
{% block body_block %}
<h1>Welcome to the index page</h1>
<h2>This is the html jawe </h2>

<h1>{{ text|upper }}</h1>
<h1>{{ number|add:"99" }}</h1>
<h1>{{ text|cut:"hello" }}</h1>
{% endblock%}

learning_templates/templates/basicapp/other.html
<!DOCTYPE html>

{% extends "basicapp/base.html" %}
{% block body_block %}
 <h1>Welcome to others page</h1>
 <h2>This is an examble of template inheritance</h2>
{% endblock %}

learning_templates/templates/basicapp/relurltemplates.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>Document</title>
 </head>
 <body>
     <h1>The relative url template page</h1>
     <a href="{% url 'basicapp:other' %}">the other page</a>
     <a href="{% url 'admin:index' %}">The admin Page</a>
     <a href="{% url 'index' %}">The index page</a>
 </body>
 </html>